# Generated by Django 5.1.6 on 2026-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID.')),
                ('name', models.CharField(help_text='Truckstop display name.', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.FloatField(help_text='Retail price in USD per gallon.')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'db_table': 'fuel_stations',
                'ordering': ['state', 'city', 'retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx'), models.Index(fields=['retail_price'], name='fuel_statio_retail__463e8c_idx')],
            },
        ),
    ]
